### ISSUE TITLE
Two questions about type abstracts

### ISSUE THREAD

**Issue by vonagam** [hxdefold/hxdefold#22]
I am new to haxe and in the process of writing lua extern definitions. Looking at abstract types  definitions in hxdefold i don't understand two things:

1) Why [`extern abstract`](https://github.com/hxdefold/hxdefold/blob/461eb3f9b098f7937911f4c5cc5cb93241cc660b/src/defold/types/Vector3.hx#L7)? I understand `enum extern abstract`, but what `extern` changes in this case, shouldn't it be simply an abstract?

2) In lua untyped interpolation [calls](https://github.com/hxdefold/hxdefold/blob/461eb3f9b098f7937911f4c5cc5cb93241cc660b/src/defold/types/Vector3.hx#L10) variables are wrapped in additional round brackets. Why are they needed? Can't create the case when they would be necessary by looking at lua compiled from haxe.

**Comment by nadako** [comment]
Hi,

Honestly, I don't quite remember why I used `extern` abstract. I _think_ it will always force the inlining, which is kind of what we want here.

Regarding brackets, I think there can be some cases with operator precedence where they would help.

**Comment by vonagam** [comment]
Thanks for fast response. Seems then that i don't miss anything. I though about precedence, but when i look at the code i see that this:
```hx
var foo = new Point();
var bar = new Point();
var baz = bar + 3 - 4;
var qux = foo - bar + baz;
```
is transformed into this:
```lua
local this1 = Point();
local foo = this1;
local this2 = Point();
local bar = this2;
local this3 = bar + 3;
local baz = this3 - 4;
local this4 = foo - bar;
local qux = this4 + baz;
```
So looks like haxe ensures precedence by splitting statements into separate lines.

Last off topic question - i saw that you tried to integrate hashlink into godot one year ago and you have `godot-hashlink` which has last commit of 3 years age, so i assume you do not plan to publish your last attempt?

**Comment by nadako** [comment]
I don't want to rely too much on tempvaring. I think they are only not optimized away because of `untyped`. I don't remember if there's `lua.Syntax.code` already, but if there is - that would be used instead and that would probably enable packing tempvars back, which could introduce precedence issues. Anyway, is there any harm done by the parens there?

Regarding Godot, yeah, I have like 3 unfinished attempts on integrating HL into that, but I couldn't really find time and motivation for that, because I don't use Godot and it's also quite hard for me to check whether some approach will work correctly and be useful/not-awkward in real world.

**Comment by vonagam** [comment]
No harm. Just trying to increase my understanding about what can be expected from haxe. In this case, i am trying to figure out if tempvaring is always implied or not. Tried with overloads that do not use `untyped` and still got it.

Pity about Godot.

Thanks for quick answers.
