### ISSUE TITLE
is running "haxe build.hxml" in the terminal necessary for every change?

### ISSUE THREAD

**Issue by thawri1** [hxdefold/hxdefold#40]
I must run "haxe build.hxml" each time to see my changes. is this a common use case or have I missed some things?
If this is always required, is there a way to do it automatically?

**Comment by haath** [comment]
Hey, yes `haxe build.hxml` needs to be called every time your Haxe sources change.

It's not necessary to do it manually every time though, since Defold supports setting editor hooks.
You just need an `on_build_started` hook that compiles your Haxe.

You can copy/paste the suggested one from [the wiki](https://github.com/hxdefold/hxdefold/wiki#workflow).

**Comment by thawri1** [comment]
thank you @haath .
I suggest mentioning in the README file that the Wiki section is available for more details.

**Comment by thawri1** [comment]
I had to close and open Defold Editor to automate Haxe compilation works.
it took me about one hour to find it out.
of course, this relates to Defold and not Hxdefold.

the process is this:
create a file in the root project directory with name of "hooks.editor_script".
with the content of:

```
local M = {}
function M.on_build_started(opts)
    return {
      {
        action = "shell",
        command = { "haxe", "build.hxml" }
      }
    }

  end
return M
```

And then close and reopen Defold and Code Editors.

**Comment by haath** [comment]
> I suggest mentioning in the README file that the Wiki section is available for more details.

Only reason it's not there yet is because the Wiki is WIP and refers to the [v2 branch](https://github.com/hxdefold/hxdefold/pull/37). I also definitely suggest using that branch if you are now starting out with hxdefold.

> I had to close and open Defold Editor

There is also a `Reload editor scripts` button somewhere on the toolbar in the editor.
Added a mention to this now in the wiki.

---

Actually your issue helped me realize that the `haxelib run hxdefold init` command should probably also generate the `hooks.editor_script` file :sweat_smile:
