### ISSUE TITLE
Optional float arguments should have a default value of 0

### ISSUE THREAD

**Issue by juxta-tad** [hxdefold/hxdefold#41]

**Comment by haath** [comment]
Hey, could you point out which functions you mean?

**Comment by juxta-tad** [comment]
Go.animate(".", GoProperties.eulerX, GoPlayback.LoopForward, 360, GoEasing.InOutQuad, 12);
		
		this does not work, had to set it to
		
		static inline function animate<T>(url:HashOrStringOrUrl, property:Property<T>, playback:GoPlayback, to:T, easing:EitherType<GoEasing,Vector>, duration:Float, ?delay:Float = 0, ?completeFunction:(Url, Property<T>)->Void):Void

**Comment by haath** [comment]
Ah you are right.

To clarify though: the correct default here is actually not `0`, but to pass no argument at all.

But since V2 I started doing this inline intermediate to redirect the callback, which caused `null` to always be passed when the argument was missing.

I will push a fix now that defaults it to `0`.
